apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: xerothermic-wallaby-python-gitops-repository
spec:
  url: https://github.com/rhtap-hub/xerothermic-wallaby-python-gitops